### ISSUE TITLE
Error when opening request unit GUI

### ISSUE THREAD

**Issue by runedog48** [DUWS-R-Team/DUWS-R#113] opened 2015-08-23 23:35 UTC
When you first open the GUI to request more units and unlock upgrade you get presented with the error
"no entry steam\__cur_sp.atlis\description.ext/ressourceheader/controls/unitlistbox.ComboScrollBar'."

I'm not sure if this error removes functionality. I feel like I am missing units.

**Comment by runedog48** [comment] 2015-08-23 23:39
I noticed in one of the most recent issues ( and judging by the activity dates ) that DUWS-R's development is pretty much halted. Luckily I'm a programmer but I've yet to check out ARMA 3's capabilities. I'll try to fix the issue myself, but I can't guarantee anything.

**Comment by runedog48** [comment] 2015-08-24 00:01
I found the fix, I believe they renamed the scrollbar class to ComboScrollBar. You need to go into the defines.hpp in the dialog folder and change every instance of "ScrollBar" to "ComboScrollBar".

**Comment by fritogotlayed** [comment] 2015-08-24 12:34
Awesome! Thanks for the tip. If you'd like to create a PR for the fix to have some credit that'd be awesome. If not I can push the change in when I get a chance. 

In all seriousness this was really bugging me and if this is the fix I can't thank you enough! I'll see if I can get on this week and make the update.

**Comment by fritogotlayed** [comment] 2015-08-24 12:35
This is a duplicate of #11 I believe

**Comment by dgrrr** [comment] 2015-09-10 06:38
Every instance, including changing
    colorScrollbar[] = {0.023529,0,0.0313725,1};
to
    colorComboScrollbar[] = {0.023529,0,0.0313725,1};

?

**Comment by fritogotlayed** [comment] 2015-09-25 00:40
@dgrrr @runedog48 Thanks for the fix here. Testing worked locally so I'll be pushing the patch here shortly.

**Closed** 2015-09-25 00:43 UTC
